jenkins:
  systemMessage: "Jenkins configured as code!"
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin1"
          password: "${admin_password}"

  mode: NORMAL
  
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false


unclassified:
  location:
    url: "https://jenkins.csye7125.xyz/"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "git-credentials"
              description: "GitHub Credentials"
              username: "${file:///var/lib/jenkins/secrets/github_username}"
              password: "${file:///var/lib/jenkins/secrets/github_password}"
              scope: GLOBAL
          - usernamePassword:
              id: "docker-credentials"
              description: "Docker Credentials"
              username: "${file:///var/lib/jenkins/secrets/docker_username}"
              password: "${file:///var/lib/jenkins/secrets/docker_password}"
              scope: GLOBAL
          # - string:
          #     scope: GLOBAL
          #     id: "shalom-PAT"
          #     secret: "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"
          #     description: "PAT token for Jenkins to authenticate with Github to post pipeline status."

jobs:
  - file: "/var/lib/jenkins/jobs/infra-status-check.groovy"
  - file: "/var/lib/jenkins/jobs/static-site-image.groovy"
  - file: "/var/lib/jenkins/jobs/pr-commit-validation-check.groovy"

