name : create a new image
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  
jobs:
  create-AMI: 
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: '1.8.0'
      
      - name: Run `packer init`
        id: init
        run: "packer init ./packer/ami.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/ami.pkr.hcl"

      - name: Run `packer build`
        id: build
        run: "packer build ./packer/ami.pkr.hcl"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}


