name: packer image Continous integration

on: 
  pull_request:
    branches:
      - main
jobs:
  validate-packer-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: '1.8.0'
    
    - name: Run `packer init`
      id: init
      run: "packer init ./image.pkr.hcl"

    - name: Run `packer validate`
      id: validate
      run: "packer validate ./image.pkr.hcl"