name: packer image Continous integration

on: 
  pull_request:
    branches:
      - main
jobs:
  validate-packer-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: '1.8.0'
    
    - name: Run `packer init`
      id: init
      run: |
        cd packer
        packer init .

    - name: packer check format
      id: check-format
      run: |
        cd packer
        packer fmt -check .

    - name: Run `packer validate`
      id: validate
      run: |
        cd packer
        packer validate -var "github_password={{secrets.GH_PASSWORD}}" -var "docker_password={{secrets.DOCKER_PASSWORD}}" .